= An unofficial Unreal Engine client for Voxta

_Made in collaboration with https://twitter.com/DZnnah[DZnnah]_ +
_This client is not affiliated, associated, endorsed by, or in any way officially connected to Voxta.ai_ +

For a raw C++ implementation, please refer to https://github.com/grrimgrriefer/TalkToMeCPP[TalkToMeCPP (Windows c++)] +

== Third party code Licenses

. SignalR client (MIT license): link:Source/SignalR/License.txt[LICENSE] +
. RuntimeAudioImporter (MIT licensed): link:Source/AudioUtility/Public/RuntimeAudioImporter/LICENSE.txt[LICENSE] +

== Optional dependencies

. OVR lipsync: link:todo-add-url-here[OVR lipsync fork] +

== Dev Progress

Trello board: +
https://trello.com/b/Biv7Si4l/unrealvoxta

== Example project

Full project including all relevant dependencies. (MIT license) + 
https://dev.azure.com/grrimgrriefer/_git/UnrealVoxtaTestProject 

== Video tutorial

Video on how to install & use the alpha release 0.0.1a +
todo-add-url-here

=== Quick-start blueprints

The plugin contains several 'minimal' plugins to help demonstrate the usage. These are not required to be used but can help as 
a guidance on how to implement certain features. +
link:Content/ExampleSetup[Example setup] +
Tutorial video: TODO

=== Blueprint usage

==== VoxtaClient
ActorComponent that 'owns' the main connection and manages the state of the client in order to communicate with the VoxtaServer. + 

TODO: images that show the main utilities

==== VoxtaAudioInput
ActorComponent that 'owns' the connection between the microphone and the VoxtaServer. + 

TODO: images that show the main utilities

==== VoxtaAudioPlayback
ActorComponent that can be used to play the audio for one (1) character. Multiple components an be used for multiple character scenarios. + 

TODO: images that show the main utilities
