blank_issues_enabled: true
contact_links:
  - name: Voxta official website
    url: https://voxta.ai/
    about: Voxta official website (unaffiliated)
  - name: DZnnah
    url: https://x.com/DZnnah
    about: My best friend, now & forever