// Copyright(c) 2024 grrimgrriefer & DZnnah, see LICENSE for details.

#pragma once

#include "CoreMinimal.h"
#include "ServerResponseBase.h"

/**
 * ServerResponseChatMessageBase
 * Abstract read-only data struct containing the shared relevant data for all 'reply...' responses
 * from the VoxtaServer (e.g., message start, chunk, end, cancelled).
 * Provides message type, message ID, and session ID.
 */
struct ServerResponseChatMessageBase : ServerResponseBase
{
#pragma region helper classes
public:
	/** Contains the possible states of the message that is currently being generated by Voxta. */
	enum class ChatMessageType
	{
		MessageStart,
		MessageChunk,
		MessageEnd,
		MessageCancelled
	};
#pragma endregion

#pragma region public API
public:
	/**
	 * Construct a base chat message response.
	 *
	 * @param messageType The type of the chat message (start, chunk, end, cancelled).
	 * @param messageId The unique ID of the message.
	 * @param sessionId The session ID this message belongs to.
	 */
	explicit ServerResponseChatMessageBase(
		ChatMessageType messageType,
		FGuid messageId,
		FGuid sessionId) : ServerResponseBase(ServerResponseType::ChatMessage),
		MESSAGE_TYPE(messageType),
		MESSAGE_ID(messageId),
		SESSION_ID(sessionId)
	{}
#pragma endregion

#pragma region data
public:
	/** The type of this chat message (start, chunk, end, cancelled). */
	const ChatMessageType MESSAGE_TYPE;
	/** The unique ID of the message. */
	const FGuid MESSAGE_ID;
	/** The session ID this message belongs to. */
	const FGuid SESSION_ID;
#pragma endregion
};